### ISSUE TITLE
help and configuration missing

### ISSUE THREAD

**Issue by adilhaimoura** [fredcox/gonhang#1]
It is not clear for me how this should work.. I do not want it to show on the left side for example!! I want to put it on right!
I want to add network and a background color with transparency!!
no help!!
no  --help
no -- config

**Comment by fredcox** [comment]
> It is not clear for me how this should work.. I do not want it to show on the left side for example!! I want to put it on right!
> I want to add network and a background color with transparency!!
> no help!!
> no --help
> no -- config

Hi,

I am sorry, but gonhang is beta version. But, if you want configure it is easy on GonhaNG System tray icon. Please, see the image below:
![mainmenu](https://user-images.githubusercontent.com/65084421/93092936-7653d200-f676-11ea-9e2a-0a59f6601160.png)

**Comment by fredcox** [comment]
> It is not clear for me how this should work.. I do not want it to show on the left side for example!! I want to put it on right!
> I want to add network and a background color with transparency!!
> no help!!
> no --help
> no -- config

GonhaNG is background color with transparency by default. I dont know what kind off Desktop Environment you are using, but it is not normal, because GonhaNG run kde, xfce, cinnamon, mate, lxqt, and much more. 

No rice DE´s like i3wm is good choose ok?

**Comment by fredcox** [comment]
> It is not clear for me how this should work.. I do not want it to show on the left side for example!! I want to put it on right!
> I want to add network and a background color with transparency!!
> no help!!
> no --help
> no -- config

GonhaNG is a monitor with easy configuration, no necessary edit files with config params, and adjusts for visual. But the interface by the wall is only this, maybe in the next interation off development, i will put support to themes. But no option to put different color and fonts, no.

**Comment by fredcox** [comment]
I can configure on the fly is:

- Position (left, center, right)
- Weather
- Network
- CPU temperature
- Nvidia card (if you have)
- partitions
- Temperatures from nvme and hdd/ssd satas. (you need hddtemp as daemon). If you not run hddtemp as daemon, no magic.

**Comment by fredcox** [comment]
I wrote this article in another language and translate for you, please read:

[
https://translate.google.com/translate?sl=pt&tl=en&u=https%3A%2F%2Ffredcox.github.io%2Fgonhang-install-linux&result=Obter+Tradu%C3%A7%C3%A3o](
https://translate.google.com/translate?sl=pt&tl=en&u=https%3A%2F%2Ffredcox.github.io%2Fgonhang-install-linux&result=Obter+Tradu%C3%A7%C3%A3o)

**Comment by adilhaimoura** [comment]
Thank you

**Comment by fredcox** [comment]
> Thank you

@adilhaimoura , i update the README.md now, no complete information, but later it will be ok.
