### ISSUE TITLE
Quantidade de dados entrada/saída da rede.

### ISSUE THREAD

**Issue by msteles** [fredcox/gonhang#2]
Saudações!
Na parte da rede, a quantidade de dados, entrada e saída não está invertida? Me parece que sim.

**Comment by fredcox** [comment]
> 
> 
> Saudações!
> Na parte da rede, a quantidade de dados, entrada e saída não está invertida? Me parece que sim.

Irei verificar isso amigo, mas acredito que não.

**Comment by fredcox** [comment]
> Saudações!
> Na parte da rede, a quantidade de dados, entrada e saída não está invertida? Me parece que sim.

Olá amigo, realmente não está acontecendo a troca.  Esses dados relativos à entrada e saída de dados da rede são obtidos do kernel mesmo, ou seja, é o core que dá essa informação para o gonhang. Fiz até um teste aqui por via das dúvidas , fiz um download e verifiquei, está tudo ok.

**Comment by fredcox** [comment]
> Saudações!
> Na parte da rede, a quantidade de dados, entrada e saída não está invertida? Me parece que sim.

Meu amigo, você tem razao, muito obrigado por ter avisado, estava invertido sim, no lugar do bytes_sent estavam os bytes_rcv e vice versa. 

Isso acabou de ser corrigido e já há a release 0.3.2 com o fix. 

mais uma vez obrigado.

**Comment by msteles** [comment]
Valeu! E mais uma vez, parabéns pelo trabalho!
