### ISSUE TITLE
Sinal de % na barra de temperatura

### ISSUE THREAD

**Issue by msteles** [fredcox/gonhang#3]
Saudações! Acho que fica meio estranho o sinal de porcentagem (%) na barra de temperatura do processador.

**Comment by fredcox** [comment]
> Saudações! Acho que fica meio estranho o sinal de porcentagem (%) na barra de temperatura do processador.

Saudações, meu amigo @msteles . vc tem razão, de fato, vou trocar para graus celsius.

**Comment by fredcox** [comment]
> Saudações! Acho que fica meio estranho o sinal de porcentagem (%) na barra de temperatura do processador.

Amigo, acabei de lançar a release 0.3.6, eu coloquei a progress bar indicando graus celsius e aproveitei e corrigi um bug que havia no espaço vertical dos itens relativos as partições. 

abraços.,

**Comment by msteles** [comment]
Legal!!! Não brinca em serviço hein!!? Valeu!!

**Comment by fredcox** [comment]
> Legal!!! Não brinca em serviço hein!!? Valeu!!

ahuahauhauhau.....

valeu!
